/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LeftMenus: typeof import('./src/components/leftMenus/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleBar: typeof import('./src/components/titleBar/index.vue')['default']
    UserIcon: typeof import('./src/components/userIcon/index.vue')['default']
  }
}
